### ISSUE TITLE
AC3 preferred audio codec not working

### ISSUE THREAD

**Issue by ericp1337** [philiptn/mkv-auto#24]
I was testing out this project with some files I have and I noticed when specifying AC3 as the preferred audio codec it never finds an existing audio track even though one exists.

<img width="887" alt="Screenshot 2024-05-17 at 9 38 29 PM" src="https://github.com/philiptn/mkv-auto/assets/2096910/dfe68be5-4ea7-4629-ab24-861f4857ab39">

Unfortunately I don't know python too well, otherwise I would make a PR. 

I think the best way to fix this bug is by making sure to transform the value used to find the AC3 track to include the `-` when `AC3` is specified in the config file in order to maintain backwards compatibility. Otherwise, I think it might be more reliable to find the audio tracks by the `codec_id` value since those are probably more consistent?

**Comment by philiptn** [comment]
The function already uses `codec_id` to match the codec pref in `user.ini`, so that part of the logic should work fine ("`AC3`" would be a substring of "`A_AC3`"). The problem was in another portion of the code, which now has been fixed in the newest [release](https://github.com/philiptn/mkv-auto/releases/tag/v1.0.2) (v1.0.2). If the problem still occurs, feel free to re-open the issue.

**Comment by ericp1337** [comment]
Thanks, seems like it's working for me so far. 🙂
